export const fieldTypes =  {
  TYPE_STATUS: 'status',
  TYPE_PRIORITY : 'priority',
  TYPE_LAYER : 'layer',
  TYPE_PARENT_TICKET : 'parent_ticket',
  TYPE_PROGRESS : 'progress',
  TYPE_ASSIGNEE : 'assignee',
  TYPE_WATCHERS : 'watchers',
  TYPE_SEPARATOR : 'separator',
  TYPE_START_DATE : 'start_date',
  TYPE_DUE_DATE : 'due_date',
  TYPE_ESTIMATE : 'time_estimate',
  TYPE_TIME_SPENT : 'time_spent',

  TYPE_DATE : 'date',
  TYPE_TIME : 'time',
  TYPE_SHORT_TEXT : 'short_text',
  TYPE_LONG_TEXT : 'long_text',
  TYPE_NUMERAL : 'numeral',
  TYPE_DECIMAL : 'decimal',
  TYPE_CHECKBOX : 'checkbox',
}

export default {
  defaultFields: [
    {
      'type': fieldTypes.TYPE_STATUS,
      'name': 'Status',
      'placeholder': '',
      'disabled': false,
      'selected': true,
    },
    {
      'type': fieldTypes.TYPE_PRIORITY,
      'name': 'Priority',
      'placeholder': '',
      'disabled': false,
      'selected': true,
    },
    {
      'type': fieldTypes.TYPE_LAYER,
      'name': 'Layer',
      'placeholder': '',
      'disabled': false,
      'selected': true,
    },
    {
      'type': fieldTypes.TYPE_PARENT_TICKET,
      'name': 'Parent ticket',
      'placeholder': '',
      'disabled': false,
      'selected': true,
    },
    {
      'type': fieldTypes.TYPE_PROGRESS,
      'name': 'Progress',
      'placeholder': '',
      'disabled': false,
      'selected': true,
    },
    {
      'type': fieldTypes.TYPE_ASSIGNEE,
      'name': 'Assignee',
      'placeholder': '',
      'disabled': false,
      'selected': true,
    },
    {
      'type': fieldTypes.TYPE_WATCHERS,
      'name': 'Watchers',
      'placeholder': '',
      'disabled': false,
      'selected': true,
    },
    {
      'type': fieldTypes.TYPE_START_DATE,
      'name': 'Start Date',
      'disabled': false,
      'placeholder': '',
      'selected': true,
    },
    {
      'type': fieldTypes.TYPE_DUE_DATE,
      'name': 'Due Date',
      'placeholder': '',
      'disabled': false,
      'selected': true,
    },
    {
      'type': fieldTypes.TYPE_ESTIMATE,
      'name': 'Estimate',
      'placeholder': '',
      'disabled': false,
      'selected': true,
    },
    {
      'type': fieldTypes.TYPE_TIME_SPENT,
      'name': 'Time spent',
      'placeholder': '',
      'disabled': false,
      'selected': true,
    }],
  customFields: [
    {
      'type': fieldTypes.TYPE_DATE,
      'name': '',
      'placeholder': 'Enter field name*',
      'disabled': false,
      'selected': false,
    },
    {
      'type': fieldTypes.TYPE_TIME,
      'name': '',
      'placeholder': 'Enter field name*',
      'disabled': false,
      'selected': false,
    },
    {
      'type': fieldTypes.TYPE_SHORT_TEXT,
      'name': '',
      'placeholder': 'Enter field name*',
      'disabled': false,
      'selected': false,
    },
    {
      'type': fieldTypes.TYPE_LONG_TEXT,
      'name': '',
      'placeholder': 'Enter field name*',
      'disabled': false,
      'selected': false,
    },
    {
      'type': fieldTypes.TYPE_NUMERAL,
      'name': '',
      'placeholder': 'Enter field name*',
      'disabled': false,
      'selected': false,
    },
    {
      'type': fieldTypes.TYPE_DECIMAL,
      'name': '',
      'placeholder': 'Enter field name*',
      'disabled': false,
      'selected': false,
    },
    {
      'type': fieldTypes.TYPE_CHECKBOX,
      'name': '',
      'placeholder': 'Enter field name*',
      'disabled': false,
      'selected': false,
    }],
  spFields: [{
    'type': fieldTypes.TYPE_SEPARATOR,
    'name': '',
    'placeholder': 'Enter separator name (optional)',
    'disabled': false,
    'selected': false,
  }],
}
